Tags3
csc302-distributed-suffering/parajuniper-project-2 pull request #24
Opened 2021-12-05 18:29 UTC by liangfe5

2021-12-05 18:35 UTC, vicchig approved these changes

2021-12-05 18:38 UTC, nikita-sh requested changes

2021-12-05 18:38 UTC, nikita-sh commented on src/client/src/App.js
> +              {/* <div id='searchbar'>
Getting some style issues on my screen:
![image](https://user-images.githubusercontent.com/36054510/144759131-35512d0f-9264-44c7-a5d3-09950d97c9f1.png)

2021-12-06 03:17 UTC, nikita-sh approved these changes
LGTM

2021-12-06 03:22 UTC, merged